language: java

jdk:
  - oraclejdk8

sudo: false

## export GPG details
before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install: mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script: mvn clean verify -Dgpg.skip -DskipTests=true -B -U

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./travis-ci/deploy.sh